#!/bin/bash
# File: installation
# This file is for the purpose of installing user-defined packages
# Reference: https://wiki.archlinux.org/title/Pacman (--needed, --noconfirm)

file_path=$1

if [[ -f $file_path ]]; then
	pacman -S --needed --noconfirm $(< "$file_path")
else
	echo "The file '$file_path' does not exist."
	exit 1
fi
