#!/bin/bash
# FILE: installation
# NOTE: This file is for the purpose of installing user-defined packages

# START HERE WITH SETTING VARIABLES IF APPLICABLE:

file_path="$SUDO_HOME/Project-01/packages" # Set packages filename

# MAIN SCRIPT:

if [[ -f $file_path ]]; then # Checks if packages exist.
	pacman -S --needed --noconfirm $(< "$file_path") # Install packages as needed without prompts. Reads each line in packages and substitutes "$file_path" place. 
else
	echo "The file '$file_path' does not exist." # Prompts an error message if designated file path does not exist. 
	exit 1 # Exits the script. 
fi

# REFERENCE: 
# https://wiki.archlinux.org/title/Pacman suggest the use of --needed to install packages as needed and --noconfirm to install without prompts
# https://www.gnu.org/software/bash/manual/bash.html suggest the use of $(< to read the entire file and substitues its place.
# https://linuxcommand.org/lc3_man_pages/sudo8.html suggest the use of $SUDO_HOME to access the home directory. 