#!/bin/bash
# FILE: link
# NOTE: This script checks if Git repository exist and performs binary and symbolic link scripting.

# START HERE WITH SETTING VARIABLES IF APPLICABLE:

home_directory="$SUDO_HOME"  # Path to the directory where you want to store the repository

# MAIN SCRIPT:

# GIT CLONING SCRIPT:

if [[ -d "$home_directory" ]]; then # Checks if the directory exists. 
    if [[-d "$home_directory/.git" ]]; then # Checks if the .git directory exists. 
    echo "Repository $home_directory is already a .git directory." 
    else
    echo "Repository already exists in $home_directory."
    fi
else
    echo "Repository not found. Creating folder and cloning repository."
    mkdir -p "$home_directory"  # Create the directory if it doesn't exist. 
    git init
    git clone "https://gitlab.com/cit2420/2420-as2-starting-files.git" "$home_directory"  # Clones repository from provided link.
fi

# SYMBOLIC LINK SCRIPT:

# Create an array of directories to link in parallel.
targets=( # Setting parallel array for targets.
    "$home_directory/bin"
    "$home_directory/config"
    "$home_directory/bashrc"
    "$home_directory/kakrc"
    "$home_directory/tmux.conf"
)

destinations=( # Setting parallel array for destinations.
    "$HOME/bin"
    "$HOME/.config"
    "$HOME/.bashrc"
    "$HOME/.config/kak/kakrc"
    "$HOME/.config/tmux/tmux.conf"
)

for i in "${!targets[@]}"; do # Loop for each target and destination.
    target="${targets[$i]}" # Assign target variable.
    destination="${destinations[$i]}" # Assign destination variable.

    if [[ ! -L "$destination" ]]; then # Check if symbolic link exists.
        ln -s "$target" "$destination" # Create symbolic link. 
        echo "Symbolic link $destination created." 
    else
        echo "Symbolic link $destination already exists."
    fi
done

# REFERENCES:
# https://ss64.com/bash/syntax-file-operators.html suggest -d option to check if directory exists.
# https://ss64.com/bash/ln.html suggest -s option to make symbolic links.
# https://ss64.com/bash/symlink.html suggest -L option to check if symbolic link exists.