#!/bin/bash
# FILE: new-user
# NOTE: This script will create a new user using the following:
# - A specified shell
# - A home directoy created
# - Clone /etc/skel
# - Addition of groups
# - Setup password

# MAIN SCRIPT:

if [[ $EUID -ne 0 ]]; then # Checks for root privileges
	echo "You need the correct privileges to run this script." # Prompts message that you require correct privileges.
	exit 1 # Exit the script.
fi

user_name=""
shell="/bin/bash"
groups=""
password=""
home_file="/home/$user_name"
UID_RANGE_1_MIN=1000 # Sets minimum of first set of UID range. 
UID_RANGE_1_MAX=65533 # Sets maximum of first set of UID range.
UID_RANGE_2_MIN=65535 # Sets minimum of second set of UID range.
UID_RANGE_2_MAX=4294967294 # Sets maximum of second set of UID range.

help() { # Help function to provide information on how to use the script.
	echo "How to use script: new-user -u <username> -s <shell> -g <groups> -p <password>"
	echo "Available functions:"
	echo "-u for Username"
	echo "-s for Shell"
	echo "-g for Groups"
	echo "-p for Password"
	exit 0

}

# MAIN SCRIPT:

while getopts ":u:s:g:p:" opt; do # Options for user_name, shell, groups, and password.
    case "${opt}" in
        u)
            user_name=${OPTARG}  # Assign username.
            ;;
        s)
            shell=${OPTARG}  # Assign shell.
            ;;
        g)
            groups=${OPTARG}  # Assign groups.
            ;;
        p)
            password=${OPTARG}  # Assign password.
            ;;
		h)
			help # Calls help function.
			;;
        :)
            echo "Cannot have no input."
            exit 1
            ;;
        ?)
            echo "Invalid option."
            exit 1
            ;;
    esac
done

if [ -z "$user_name" ]; then
    echo "Username is required."
    exit 1
fi

random_uid() { # Function to loop through a sequence of random UID and checks if they are in /etc/passwd and /etc/group.
while true; do
        if [[ $((RANDOM % 2)) -eq 0 ]]; then
            uid=$((RANDOM % (UID_RANGE_1_MAX - UID_RANGE_1_MIN + 1) + UID_RANGE_1_MIN)) # Generates random UID within first set of range..
        else
            uid=$((RANDOM % (UID_RANGE_2_MAX - UID_RANGE_2_MIN + 1) + UID_RANGE_2_MIN)) # Generates random UID within second set of range.
        fi
        if ! grep -q ":$uid:" /etc/passwd && ! grep -q ":$uid:" /etc/group; then # Checks if UID is not in /etc/passwd and /etc/group.
            echo "$uid"
            return
        fi
    done
}

UID=$(random_uid)
mkdir "$home_file"
cp -r /etc/skel/. "$home_file"
chown -r "$user_name:$uid" "$home_file"
chmod -r 700 "$home_file"

if [ -n "$groups" ]; then
    for group in $(echo "$groups" | tr "," "\n"); do
        # Check if the group exists, if not, create it manually
        if ! grep -q "^$group:" /etc/group; then
	fi
	done
fi

# REFERENCES:
# https://www.tutorialspoint.com/guide-to-generate-random-numbers-in-linux suggest to use RANDOM to generate random numbers.
# https://www.geeksforgeeks.org/random-shell-variable-in-linux-with-examples/ suggest to use RANDOM to generate random numbers.