#!/bin/bash
# FILE: new-user
# NOTE: This script will create a new user using the following:
# - A specified shell
# - A home directoy created
# - Clone /etc/skel
# - Addition of groups
# - Setup password

# MAIN SCRIPT:

if [[ $EUID -ne 0 ]]; then # Checks for root privileges
	echo "You need the correct privileges to run this script." # Prompts message that you require correct privileges.
	exit 1 # Exit the script.
fi

user_name=""
shell="/bin/bash"
groups=""
password=""

help() {

}

# MAIN SCRIPT:

while getopts ":u:s:g:p:" opt; do
    case "${opt}" in
        u)
            user_name=${OPTARG}  # Assign username.
            ;;
        s)
            shell=${OPTARG}  # Assign shell.
            ;;
        g)
            groups=${OPTARG}  # Assign groups.
            ;;
        p)
            password=${OPTARG}  # Assign password.
            ;;
		h)
			help
			;;
        :)
            echo "Cannot have no input."
            exit 1
            ;;
        ?)
            echo "Invalid option."
            exit 1
            ;;
    esac
done

if [[ -z "$user_name" ]]; then
    echo "Must enter a username."
    exit 1
fi

if useradd -m -s "$shell" "$user_name"; then
    echo "User '$user_name' created successfully."
else
    echo "Failed to create user '$user_name'."
    exit 1
fi

if cp -r /etc/skel/. "/home/$user_name/"; then
    echo "Successfully copied /etc/skel to /home/$user_name/."
else
    echo "Failed to copy /etc/skel."
    exit 1
fi

if [[ -n "$password" ]]; then
    if echo "$user_name:$password" | chpasswd; then
        echo "Password set for '$user_name'."
    else
        echo "Failed to set password for '$user_name'."
        exit 1
    fi
else
    echo "Password not set. Please set it."
fi

echo "User '$user_name' has been created successfully."
exit 0



# REFERENCES:
# https://ss64.com/bash/useradd.html suggest -m option to create home directory.
# https://ss64.com/bash/groupadd.html suggest -g option to add group.
# https://ss64.com/bash/usermod.html suggest -a option to add user to group.
# https://ss64.com/bash/chpasswd.html suggest to use echo to set password.
# https://ss64.com/bash/cp.html suggest -r option to copy directories.
